services:
  postgres:
    image: postgres:17
    container_name: notification-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: notification-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  notification-service:
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    container_name: notification-service
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"

  ingestion-service:
    build:
      context: .
      dockerfile: apps/ingestion-service/Dockerfile
    container_name: ingestion-service
    env_file:
      - .env.docker
    depends_on:
      - redis
    restart: unless-stopped

    
volumes:
  postgres_data:
